* gimel
  :PROPERTIES:
  :CUSTOM_ID: gimel
  :END:

Flat file CMS in Clojure. This watches a directory for markdown and html snippets, and then transforms those into web pages for a static site. You can then either copy the resulting files to your static website, or just run this as your webserver, as it serves your static pages by default. In the future, this will have an admin page you can log into to manage it.

** Installation
   :PROPERTIES:
   :CUSTOM_ID: installation
   :END:

1. Clone this repo.
   #+BEGIN_SRC shell
   git clone https://github.com/timotheosh/gimel.git
   #+END_SRC
2. Change settings in ~gimel/resources/config/gimel.edn~ to fit your usage.
3. Run ~lein run~ or ~lein ring server~

** License
   :PROPERTIES:
   :CUSTOM_ID: license
   :END:

*** MIT License
    :PROPERTIES:
    :CUSTOM_ID: mit-license
    :END:

Copyright © 2019 Tim Hawes

Permission is hereby granted, free of charge, to any person obtaining a
copy of this software and associated documentation files (the
"Software"), to deal in the Software without restriction, including
without limitation the rights to use, copy, modify, merge, publish,
distribute, sublicense, and/or sell copies of the Software, and to
permit persons to whom the Software is furnished to do so, subject to
the following conditions:

The above copyright notice and this permission notice shall be included
in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
