* gimel
  :PROPERTIES:
  :CUSTOM_ID: gimel
  :END:

Static site generator in Clojure, with /some/ potential to become a CMS. It will also collect metadata from those files and store them in a sqlite database.

** Description
~gimel~, like most staic website generators, is an "opinionated" implementation. It fits a particular workflow. It originally watched a directory for file changes and then convert any changed files into html for a static site. I tried maintaining my websites in markdown, but becamw eutterly dissatisfied, as I had been maintaing my websites as org-mode projects. Org-mode publish became slow as the site grew, and I needed something faster. Dissatisfied with the the current state of org-mode parsers in any language, except elisp, I opted for a different path forward. So I created an Emacs package that minimally convert org-mode files into html snippets. ~gimel.el~ will properly convert links, add id's to section headers. It can be run in batch mode, but batch mode is almost as slow as org-publish. So individual files can be exported on save. File-level properties for org-mode files are saved as metadata and stored in the sqlite database.

** Installation
   :PROPERTIES:
   :CUSTOM_ID: installation
   :END:

1. Clone this repo.
   #+BEGIN_SRC shell
   git clone https://github.com/timotheosh/gimel.git
   #+END_SRC
2. Change settings in ~gimel/resources/config/gimel.edn~ to fit your usage.
   You can just copy it to ~~/.config/gimel/gimel.edn~ and then make changes to it. Gimel will look for the settings file there before defaulting to the one under resources. You can also just copy it anywhere and run with ~lein run --config <path to configfile>~ or use the same parameters with the uberjar, if you so choose to compile before using it.
3. Run ~lein run~

** Future
At some point, I may use the data generated in the database as a means for generating menus and "related links" section for the sites.

** License
   :PROPERTIES:
   :CUSTOM_ID: license
   :END:

*** MIT License
    :PROPERTIES:
    :CUSTOM_ID: mit-license
    :END:

Copyright © 2019-2024 Tim Hawes

Permission is hereby granted, free of charge, to any person obtaining a
copy of this software and associated documentation files (the
"Software"), to deal in the Software without restriction, including
without limitation the rights to use, copy, modify, merge, publish,
distribute, sublicense, and/or sell copies of the Software, and to
permit persons to whom the Software is furnished to do so, subject to
the following conditions:

The above copyright notice and this permission notice shall be included
in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
