* gimel
  :PROPERTIES:
  :CUSTOM_ID: gimel
  :END:

Static site generator in Clojure, with /some/ potential to become a CMS. This watches a directory for markdown and html snippets, and then transforms those into web pages for a static site. Iyt will also collect metadata from those files and store them in a sqlite database.

At some point, I may use the data generated in the database as a means for generating menus and "related links" section for the sites.

** org-mode
I've been utterly disatisified with available org-mode parsers, but that is how most of my content is created. So I created an Emacs package that will properly convert links, add id's to section headers. It can be run in batch mode, but batch mode is almost as slow as org-publish. So individual files can be exported on save. File-lelev properties for org-mode files are saved as metadata and stored in the sqlite database.



** Installation
   :PROPERTIES:
   :CUSTOM_ID: installation
   :END:

1. Clone this repo.
   #+BEGIN_SRC shell
   git clone https://github.com/timotheosh/gimel.git
   #+END_SRC
2. Change settings in ~gimel/resources/config/gimel.edn~ to fit your usage.
3. Run ~lein run~ or ~lein ring server~

**

** License
   :PROPERTIES:
   :CUSTOM_ID: license
   :END:

*** MIT License
    :PROPERTIES:
    :CUSTOM_ID: mit-license
    :END:

Copyright © 2019-2024 Tim Hawes

Permission is hereby granted, free of charge, to any person obtaining a
copy of this software and associated documentation files (the
"Software"), to deal in the Software without restriction, including
without limitation the rights to use, copy, modify, merge, publish,
distribute, sublicense, and/or sell copies of the Software, and to
permit persons to whom the Software is furnished to do so, subject to
the following conditions:

The above copyright notice and this permission notice shall be included
in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
